dist: trusty

language: node_js
node_js:
  - node

services:
  - mongodb

env:
  - NODE_ENV=test

addons:
  sonarcloud:
    organization: mutoe-github

cache:
  yarn: true

install:
  - yarn

before_script:
  - cp .env.template .env

script:
  - yarn lint
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sonar-scanner; fi
