basePath: /v1
definitions:
  LoginForm:
    description: LoginForm 用户登录表单
    properties:
      email:
        type: string
        x-go-name: Email
      password:
        type: string
        x-go-name: Password
    type: object
    x-go-package: github.com/handnotes/handnote-server/api/v1
  RegisterForm:
    description: RegisterForm 用户注册表单
    properties:
      avatar_url:
        type: string
        x-go-name: AvatarURL
      birth:
        format: date-time
        type: string
        x-go-name: Birth
      code:
        format: int64
        type: integer
        x-go-name: Code
      email:
        type: string
        x-go-name: Email
      gender:
        format: int8
        type: integer
        x-go-name: Gender
      password:
        type: string
        x-go-name: Password
      phone:
        type: string
        x-go-name: Phone
      user_name:
        type: string
        x-go-name: UserName
    type: object
    x-go-package: github.com/handnotes/handnote-server/api/v1
host: localhost:9090
info:
  contact:
    email: gethin.yan@gmail.com
    name: gethin
    url: http://notes.gethin.cn
  description: Handnote 接口文档
  title: API.
  version: 0.0.1
paths:
  /auth/login:
    post:
      description: 用户登录
      operationId: loginRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/LoginForm'
      responses:
        "200":
          $ref: '#/responses/AuthResponse'
      schemes:
      - http
      - https
  /auth/register:
    post:
      description: 用户注册
      operationId: registerRequest
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/RegisterForm'
      responses:
        "200":
          $ref: '#/responses/AuthResponse'
        "400":
          $ref: '#/responses/ResponseWithMessage'
      schemes:
      - http
      - https
  /auth/sendEmail:
    get:
      description: 发送邮件
      operationId: sendEmailRequest
      parameters:
      - in: query
        name: email
        type: string
        x-go-name: Email
      - in: query
        name: user_name
        type: string
        x-go-name: UserName
      responses:
        "200":
          $ref: '#/responses/AuthResponse'
      schemes:
      - http
      - https
responses:
  AuthResponse:
    description: AuthResponse 用户注册/登录响应参数
    schema:
      properties:
        access_token:
          type: string
          x-go-name: AccessToken
      type: object
  ResponseWithMessage:
    description: ResponseWithMessage 含有message消息的响应
    headers:
      message:
        type: string
schemes:
- http
- https
swagger: "2.0"
