app:
  name: Handnote
  jwt_secret: handnote

server:
  http_port: 9091

database:
  host: 127.0.0.1
  port: 5432
  dbname: handnote_test
  user: postgres
  password: postgres
  sslmode: disable

redis:
  addr: 127.0.0.1:6379
  password:
  db: 1

email:
  from: no-reply@gethin.cn
  from_subject: Handnote
  subject: Handnote验证码

code:
  min: 100000
  max: 999999
  validity_period: 5m
